# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"source": "01_noisyimagenette.ipynb",
         "df": "01_noisyimagenette.ipynb",
         "get_inverse_transform": "01_noisyimagenette.ipynb",
         "lbl_dict": "01_noisyimagenette.ipynb",
         "lbl_dict_inv": "01_noisyimagenette.ipynb",
         "get_dls": "01_noisyimagenette.ipynb",
         "dls_5": "01_noisyimagenette.ipynb",
         "learn_5": "01_noisyimagenette.ipynb",
         "train_preds": "01_noisyimagenette.ipynb",
         "val_preds": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "train_ordered_label_errors": "01_noisyimagenette.ipynb",
         "noisy_train": "01_noisyimagenette.ipynb",
         "preds_50": "01_noisyimagenette.ipynb",
         "confidence": "01_noisyimagenette.ipynb",
         "noisy_train_50": "01_noisyimagenette.ipynb",
         "high_confident_noisy": "01_noisyimagenette.ipynb",
         "path": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "x": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "n": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "rng": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "noise_idxs": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "mnist": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "dls": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "learn": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb",
         "val_ordered_label_errors": "02_NoisyMitigation_using_LabelSmoothing_MNIST.ipynb"}

modules = ["noisyimagenette.py",
           "labelsmoothing.py"]

doc_url = "https://manisnesan.github.io/fsdl/"

git_url = "https://github.com/manisnesan/fsdl/tree/main/"

def custom_doc_links(name): return None
