# AUTOGENERATED! DO NOT EDIT! File to edit: 01_noisyimagenette.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastcore.test import *
from fastai.vision.all import *
from pathlib import Path

import pandas as pd
import fastai, fastcore, nbdev
test_eq(['2.3.0', '1.3.19', '1.1.13'], [fastai.__version__, fastcore.__version__, nbdev.__version__])